### ISSUE TITLE
Version problems

### ISSUE THREAD

**Issue by recon88** [Corosauce/Weather#1]
Not sure if it's me or not but I can't join my server because of WeatherMod.

"Forge Mod Loader could not connect to this server.
The mods and versions listed below could not be found.
They are required to play on this server.

WeatherMod : 1.591"

Server log says the same:
"Disconnecting recon88: The server requires mods that are absent or out of date on your client"

I tried redownloading everything, copied it into my client's mods folder and uploaded the same files to the server. Didn't help.
The mod shows in the modlist of the client.

**Comment by recon88** [comment]
Nervermind. Downloaded from official page again and it works.
Must be an issue in the Tropicraft package then.

**Comment by Jmasterp243** [comment]
So I'm not entirely sure if this is the right place to discuss this but when I download the 1.6.4 version of the weather1 mod, the files in the mod folder are zips and when i put them in my mods folder they don't load when I launch Minecraft with forge. Is it because they are not jar files?
