### ISSUE TITLE
Tornado mod inception

### ISSUE THREAD

**Issue by Josh74000** [Corosauce/Weather#4]
![2018-02-14_17 58 06](https://user-images.githubusercontent.com/32041132/36219912-d03285ee-11b0-11e8-9040-6e9e3f4fc99a.png)
left: destructive tornadoes v0.42
right: weather and tornadoes v1.1

**Comment by Josh74000** [comment]
I figured out how to get two tornado mods working at the same time, I had to change the id's for the destructive tornadoes mod so that the weather and tornadoes mod could work with the destructive tornadoes mod.

**Comment by Josh74000** [comment]
![2018-02-14_18 03 50](https://user-images.githubusercontent.com/32041132/36220123-6d950b22-11b1-11e8-8e37-58fe3b3ef3b3.png)
LOL this happened when the destructive tornadoes mod and the newer one was inside of each other

**Comment by Josh74000** [comment]
idk

**Comment by Josh74000** [comment]
Also referring to https://github.com/Corosauce/weather2/issues/216, the 1.6.4 tornado mod works with weather2.

**Comment by Josh74000** [comment]
I'm surfing the waves with a movable surfboard, also somehow skins don't work on versions 1.6.4 and below. Also why are the waves bright? Well I have the brightness set to 200 on minecraft.
![2018-02-16_23 13 28](https://user-images.githubusercontent.com/32041132/36333562-74c83896-136f-11e8-81fa-6434081849fb.png)

**Comment by Josh74000** [comment]
![2018-02-16_23 19 16](https://user-images.githubusercontent.com/32041132/36333636-d4e61cf2-136f-11e8-926e-3eee573e84df.png)
Also a tornado formed at the end of a normal rainstorm. That should've been fixed, well it was, but it returned.

**Comment by Josh74000** [comment]
could you also update https://coros.us/mods/tornadoes so that the older versions on it are there (this includes the 1.6, 1.5, 1.4, 1.3, 1.2, 1.1, 1.0.0, beta 1.8.1 ans beta 1.7.3 versions).

**Comment by tornadocentral09** [comment]
dude what have you done?- lol how is that even possible
